#!/usr/bin/env node
// Regenerates src/*-wasm-bytes.generated.ts from wasm/*.wasm (base64-embedded
// so the compiled kernels ship inside dist/ — npm publish never depends on a
// separate binary asset being present at a guessed runtime path).
//
// Run after rebuilding the kernel:
//   yarn workspace @ac-kit/crypto-safe build-wasm
// (already calls this script as its last step)
//
// The generated files ARE committed — unlike wasm/*.wasm (gitignored, Rust
// toolchain required to rebuild), a plain `git clone && yarn install` must be
// enough to produce a working published package with no Rust involved.

import { readFile, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";

// `new URL("..", ...)` keeps a trailing slash; drop it so joins below don't double up.
const packageRoot = fileURLToPath(new URL("..", import.meta.url)).replace(
	/\/$/,
	"",
);

const MODULES = [
	{
		wasmPath: `${packageRoot}/wasm/fixed_uint.wasm`,
		outPath: `${packageRoot}/src/kernel/wasm/_wasm-bytes.generated.ts`,
	},
];

for (const { wasmPath, outPath } of MODULES) {
	const bytes = await readFile(wasmPath);
	const base64 = bytes.toString("base64");

	await writeFile(
		outPath,
		`// Generated by \`yarn embed:wasm\` from \`${wasmPath.slice(packageRoot.length + 1)}\`. Do not edit by hand.\nexport default ${JSON.stringify(base64)};\n`,
	);
}
