import { existsSync, readFileSync, readdirSync } from "node:fs";
import { fileURLToPath } from "node:url";

import starlight from "@astrojs/starlight";
import { defineConfig } from "astro/config";
import { createStarlightTypeDocPlugin } from "starlight-typedoc";

const repositoryRoot = fileURLToPath(new URL("../..", import.meta.url));

const SITE_BASE = "https://anthochamp.github.io/node-essentials";

/**
 * Every `@ac-kit` workspace whose manifest claims a generated reference page.
 *
 * A package opts in by pointing its `homepage` at its own `/api/` page, which
 * makes one field the single source of truth: what npm shows a reader, what
 * this generates, and what the README links to cannot drift apart. A package
 * that ships no TypeScript, or that cannot currently be documented, points
 * `homepage` at the repository instead and is skipped here.
 */
function apiPackages() {
	const packages = [];

	for (const directory of readdirSync(`${repositoryRoot}packages`).sort()) {
		const location = `packages/${directory}`;
		const manifestPath = `${repositoryRoot}${location}/package.json`;
		if (!existsSync(manifestPath)) {
			continue;
		}

		const manifest = JSON.parse(readFileSync(manifestPath, "utf8"));
		if (
			manifest.private === true ||
			manifest.homepage !== `${SITE_BASE}/api/${directory}/`
		) {
			continue;
		}

		const candidates =
			typeof manifest.exports === "object" && manifest.exports !== null
				? Object.values(manifest.exports)
				: [manifest.main];
		const entryPoints = candidates.filter(
			(entry) =>
				typeof entry === "string" &&
				entry.endsWith(".ts") &&
				existsSync(`${repositoryRoot}${location}/${entry.slice(2)}`),
		);
		if (entryPoints.length === 0) {
			throw new Error(
				`${manifest.name} claims an API page in its homepage but exposes no TypeScript entry point.`,
			);
		}

		packages.push({
			name: manifest.name,
			slug: directory,
			location,
			entryPoints: entryPoints.map(
				(entry) => `../../${location}/${entry.slice(2)}`,
			),
		});
	}

	return packages;
}

/**
 * Subject areas the guide is organised by, in reading order.
 *
 * Deliberately not the package tree: a reader looking for a root does not know
 * it lives in `math-analysis`. One package may feed several domains and one
 * domain may draw on several packages — `src/lib/packages.ts` holds that
 * mapping. A domain is listed here only once it has at least one page.
 *
 * Sub-sections are written out rather than autogenerated from the directory
 * tree, because Starlight labels an autogenerated group with its directory name
 * and the subjects are not named after their folders.
 */
const DOMAINS = [
	{
		label: "Mathematics",
		collapsed: true,
		items: [
			{ label: "Overview", link: "/topics/math/" },
			{
				label: "Mathematical functions",
				items: [{ autogenerate: { directory: "topics/math/functions" } }],
			},
			{
				label: "Numerical calculus",
				items: [{ autogenerate: { directory: "topics/math/calculus" } }],
			},
		],
	},
];

const typeDocPlugins = [];
const apiSidebarGroups = [];

for (const { name, slug, location, entryPoints } of apiPackages()) {
	const [plugin, sidebarGroup] = createStarlightTypeDocPlugin();

	typeDocPlugins.push(
		plugin({
			entryPoints,
			tsconfig: `../../${location}/tsconfig.json`,
			output: `api/${slug}`,
			sidebar: { label: name, collapsed: true },
			// A package here has claimed an API page, so generating nothing is a
			// build failure rather than a page that quietly 404s.
			errorOnEmptyDocumentation: true,
		}),
	);

	apiSidebarGroups.push(sidebarGroup);
}

export default defineConfig({
	site: "https://anthochamp.github.io",
	base: "/node-essentials",
	srcDir: "./src",
	integrations: [
		starlight({
			title: "@ac-kit",
			description:
				"Reusable, portable-first TypeScript packages: language extensions, data structures, numeric domains, cryptography, data formats and network protocols.",
			social: [
				{
					icon: "github",
					label: "GitHub",
					href: "https://github.com/anthochamp/node-essentials",
				},
			],
			plugins: typeDocPlugins,
			sidebar: [
				{
					label: "Start here",
					items: [{ autogenerate: { directory: "start" } }],
				},
				...DOMAINS,
				{
					label: "API reference",
					collapsed: true,
					items: [
						{ label: "All symbols", link: "/reference/symbols/" },
						...apiSidebarGroups,
					],
				},
				{
					label: "Packages",
					link: "/reference/packages/",
				},
				{
					label: "Glossary",
					link: "/reference/glossary/",
				},
			],
		}),
	],
	vite: {
		server: {
			// Examples and package sources live outside this workspace's root.
			fs: { allow: [repositoryRoot] },
		},
	},
});
