// Generated from locale/fr.po by scripts/generate-names.ts. Do not edit.

import type { CssColorLabels } from "../color-labels.js";

/** The language tag these labels were written for. */
export const LOCALE = "fr";

export const CSS_COLOR_LABELS: CssColorLabels = new Map([
	["aliceblue", "Bleu Alice"],
	["antiquewhite", "Blanc antique"],
	["aquamarine", "Aigue-marine"],
	["azure", "Azuré"],
	["beige", "Beige clair"],
	["bisque", "Bisque"],
	["black", "Noir"],
	["blanchedalmond", "Amande"],
	["blue", "Bleu"],
	["blueviolet", "Bleu violet"],
	["brown", "Brun rouge"],
	["burlywood", "Bois massif"],
	["cadetblue", "Bleu cadet"],
	["chartreuse", "Chartreuse"],
	["chocolate", "Brun cacao"],
	["coral", "Corail"],
	["cornflowerblue", "Bleu bleuet"],
	["cornsilk", "Jaune maïs doux"],
	["crimson", "Cramoisi"],
	["cyan", "Cyan"],
	["darkblue", "Bleu foncé"],
	["darkcyan", "Cyan foncé"],
	["darkgoldenrod", "Jaune doré foncé"],
	["darkgray", "Gris foncé"],
	["darkgreen", "Vert foncé"],
	["darkkhaki", "Kaki foncé"],
	["darkmagenta", "Magenta foncé"],
	["darkolivegreen", "Olive verte foncé"],
	["darkorange", "Orange foncé"],
	["darkorchid", "Orchidée foncé"],
	["darkred", "Fleur de chocolat"],
	["darksalmon", "Saumon foncé"],
	["darkseagreen", "Vert océan foncé"],
	["darkslateblue", "Bleu ardoise foncé"],
	["darkslategray", "Gris ardoise foncé"],
	["darkturquoise", "Turquoise foncé"],
	["darkviolet", "Violet foncé"],
	["deeppink", "Rose profond"],
	["deepskyblue", "Bleu ciel profond"],
	["dimgray", "Gris mat"],
	["dodgerblue", "Bleu toile"],
	["firebrick", "Brique feu"],
	["floralwhite", "Blanc floral"],
	["forestgreen", "Vert forêt"],
	["gainsboro", "Gris étain"],
	["ghostwhite", "Blanc fantôme"],
	["gold", "Or"],
	["goldenrod", "Jaune doré"],
	["gray", "Gris"],
	["green", "Vert"],
	["greenyellow", "Vert jaune"],
	["honeydew", "Miellat"],
	["hotpink", "Rose vif"],
	["indianred", "Rouge indien"],
	["indigo", "Bleu-violet"],
	["ivory", "Blanc ivoire"],
	["khaki", "Kaki"],
	["lavender", "Lavande"],
	["lavenderblush", "Blanc lavande"],
	["lawngreen", "Vert pelouse"],
	["lemonchiffon", "Mousseline de citron"],
	["lightblue", "Bleu clair"],
	["lightcoral", "Corail clair"],
	["lightcyan", "Cyan clair"],
	["lightgoldenrodyellow", "Jaune doré clair"],
	["lightgreen", "Vert clair"],
	["lightgrey", "Gris clair"],
	["lightpink", "Rose clair"],
	["lightsalmon", "Saumon clair"],
	["lightseagreen", "Vert océan clair"],
	["lightskyblue", "Bleu ciel clair"],
	["lightslategray", "Gris ardoise clair"],
	["lightsteelblue", "Bleu acier clair"],
	["lightyellow", "Jaune clair"],
	["lime", "Vert citron"],
	["limegreen", "Vert citron"],
	["linen", "Blanc lin"],
	["magenta", "Magenta"],
	["maroon", "Bordeaux"],
	["mediumaquamarine", "Aigue-marine moyen"],
	["mediumblue", "Bleu moyen"],
	["mediumorchid", "Orchidée moyen"],
	["mediumpurple", "Pourpre moyen"],
	["mediumseagreen", "Vert océan moyen"],
	["mediumslateblue", "Bleu ardoise moyen"],
	["mediumspringgreen", "Vert printemps moyen"],
	["mediumturquoise", "Turquoise moyen"],
	["mediumvioletred", "Violet moyen"],
	["midnightblue", "Bleu nuit"],
	["mintcream", "Blanc menthe"],
	["mistyrose", "Rose brumeux"],
	["moccasin", "Mocassin"],
	["navajowhite", "Blanc navarro"],
	["navy", "Bleu marine"],
	["oldlace", "Blanc dentelle"],
	["olive", "Jaune olive"],
	["olivedrab", "Olivâtre"],
	["orange", "Orange"],
	["orangered", "Rouge orange"],
	["orchid", "Orchidée"],
	["palegoldenrod", "Jaune doré pâle"],
	["palegreen", "Menthe verte"],
	["paleturquoise", "Turquoise pâle"],
	["palevioletred", "Violet pâle"],
	["papayawhip", "Papaye"],
	["peachpuff", "Beige pêche"],
	["peru", "Pérou"],
	["pink", "Rose"],
	["plum", "Rouge prune"],
	["powderblue", "Bleu poudre"],
	["purple", "Patriarche"],
	["rebeccapurple", "Iris"],
	["red", "Rouge"],
	["rosybrown", "Brun rosé"],
	["royalblue", "Bleu royal"],
	["saddlebrown", "Brun cuir"],
	["salmon", "Saumon"],
	["sandybrown", "Brun sablé"],
	["seagreen", "Vert océan"],
	["seashell", "Blanc coquillage"],
	["sienna", "Terre de sienne"],
	["silver", "Argent"],
	["skyblue", "Bleu ciel"],
	["slateblue", "Bleu ardoise"],
	["slategray", "Gris ardoise"],
	["snow", "Neige"],
	["springgreen", "Vert printemps"],
	["steelblue", "Bleu acier"],
	["tan", "Brun"],
	["teal", "Bleu sarcelle"],
	["thistle", "Violet chardon"],
	["tomato", "Tomate"],
	["turquoise", "Turquoise"],
	["violet", "Violet"],
	["wheat", "Blé"],
	["white", "Blanc pur"],
	["whitesmoke", "Blanc fumée"],
	["yellow", "Jaune brillant"],
	["yellowgreen", "Jaune vert"],
]);
