import { describe, expect, it } from "vitest";

import { matchGlob } from "./compile-glob.js";

/**
 * The `"bash"` preset against real `minimatch` 10.1.1 output.
 *
 * `minimatch` is not a dependency here and never will be — these bits were
 * generated by running it once and baked in as literals, which is what makes
 * this a parity test rather than a wrapper test.
 *
 * Where the two disagree, {@link DIVERGENCES} names the pair and why. Each one
 * is asserted to still disagree, so a divergence stays a decision rather than
 * quietly becoming a regression.
 */

const INPUTS: readonly string[] = [
	"",
	"a",
	"ab",
	"abc",
	"a.ts",
	"a.tsx",
	"a.js",
	".env",
	".",
	"..",
	"a/b",
	"a/b.ts",
	"src/a.ts",
	"src/deep/a.ts",
	"ad",
	"abd",
	"acd",
	"abcd",
	"abcbd",
	"aed",
	"x/a",
	"x/b",
	"a/b/c",
	"a/c",
	"[abc]",
	"@(a|b)",
	"#comment",
	"!a",
	"xAy",
	"xay",
	"cc",
	"bc",
	"ac",
	"c",
];

const VECTORS: ReadonlyArray<readonly [string, string]> = [
	["a", "0100000000000000000000000000000000"],
	["a/b.ts", "0000000000010000000000000000000000"],
	["*.ts", "0000100000000000000000000000000000"],
	["a*", "0111111000000011111100000000000010"],
	["*a*", "0111111000000011111100001101010010"],
	["?", "0100000000000000000000000000000001"],
	["a?c", "0001000000000000000000000000000000"],
	["**/a.ts", "0000100000001100000000000000000000"],
	["a/**/b", "0000000000100000000000000000000000"],
	["**/*", "0111111000111111111111111111111111"],
	["src/**", "0000000000001100000000000000000000"],
	["[abc]", "0100000000000000000000000000000001"],
	["[!abc]", "0000000000000000000000000000000000"],
	["[^abc]", "0000000000000000000000000000000000"],
	["[a-z]", "0100000000000000000000000000000001"],
	["[[:alpha:]]", "0100000000000000000000000000000001"],
	["[[:digit:]]", "0000000000000000000000000000000000"],
	["x[[:upper:]]y", "0000000000000000000000000000100000"],
	["a.{ts,tsx}", "0000110000000000000000000000000000"],
	["{a,b}/{c,d}", "0000000000000000000000010000000000"],
	["@(a|b)", "0100000000000000000000000000000000"],
	["a@(b|c)d", "0000000000000001100000000000000000"],
	["?(a|b)", "1100000000000000000000000000000000"],
	["a?(b|c)d", "0000000000000011100000000000000000"],
	["*(a|b)", "1110000000000000000000000000000000"],
	["a*(b|c)d", "0000000000000011111000000000000000"],
	["+(a|b)", "0110000000000000000000000000000000"],
	["a+(b|c)d", "0000000000000001111000000000000000"],
	["a!(b)", "0101111000000011111100000000000010"],
	["a!(b|c)d", "0000000000000010011100000000000000"],
	["x/!(a)", "0000000000000000000001000000000000"],
	["@(*.ts|*.tsx)", "0000110000000000000000000000000000"],
	["!*.ts", "1111011111111111111111111111111111"],
	["!!a", "0100000000000000000000000000000000"],
	["#comment", "0000000000000000000000000000000000"],
	["\\!a", "0000000000000000000000000001000000"],
	["*/*", "0000000000111000000011010000000000"],
	["*", "0111111000000011111100001111111111"],
	[".*", "0000000100000000000000000000000000"],
	["a/!(b)/c", "0000000000000000000000000000000000"],
	["!(a|b)c", "1111111111111111111111111111111111"],
];

/**
 * A whole row this package answers by a different rule, with the rule named.
 * Its own expectations are asserted separately, below.
 */
const ROW_DIVERGENCES: ReadonlyMap<string, string> = new Map([
	[
		"!(a|b)c",
		"minimatch reads a leading `!` as whole-pattern negation even before `(`, leaving `(a|b)c` as literal parentheses. bash reads `!(` as the complement group, and this preset is named for the language rather than for the implementation.",
	],
]);

/** One pattern/input pair answered differently, with the reason. */
const CELL_DIVERGENCES: ReadonlyArray<readonly [string, string, string]> = [
	[
		".*",
		".",
		"minimatch refuses to let a wildcard match `.` or `..` at all. That is a path-safety rule of its own, not bash's: `echo .*` in a shell lists both.",
	],
	[
		".*",
		"..",
		"Same rule: minimatch guards `.` and `..` against a wildcard; bash does not.",
	],
	[
		"*",
		"",
		"minimatch treats a path portion as never empty, because a filename never is. This package matches strings, and `*` is any run of characters including the empty one — which is also what its other three dialects already do.",
	],
	["**/*", "", "Same rule, reached through the trailing `*`."],
];

function cellDivergence(pattern: string, input: string): string | undefined {
	return CELL_DIVERGENCES.find(
		(entry) => entry[0] === pattern && entry[1] === input,
	)?.[2];
}

describe("minimatch parity", () => {
	for (const [pattern, bits] of VECTORS) {
		const rowReason = ROW_DIVERGENCES.get(pattern);
		if (rowReason !== undefined) {
			continue;
		}
		it(`matches minimatch on ${JSON.stringify(pattern)}`, () => {
			for (const [index, input] of INPUTS.entries()) {
				const expected = bits[index] === "1";
				const actual = matchGlob(input, pattern, "bash");
				const reason = cellDivergence(pattern, input);
				const label = `${JSON.stringify(pattern)} vs ${JSON.stringify(input)}`;
				if (reason === undefined) {
					expect(actual, label).toBe(expected);
				} else {
					expect(actual, `${label} — ${reason}`).toBe(!expected);
				}
			}
		});
	}

	it("reads a leading `!(` as the complement group, the way bash does", () => {
		expect(ROW_DIVERGENCES.has("!(a|b)c")).toBe(true);
		// minimatch answers true for every one of these, having negated a literal.
		expect(matchGlob("abc", "!(a|b)c", "bash")).toBe(true);
		expect(matchGlob("cc", "!(a|b)c", "bash")).toBe(true);
		expect(matchGlob("c", "!(a|b)c", "bash")).toBe(true);
		expect(matchGlob("ac", "!(a|b)c", "bash")).toBe(false);
		expect(matchGlob("bc", "!(a|b)c", "bash")).toBe(false);
		expect(matchGlob("a", "!(a|b)c", "bash")).toBe(false);
		expect(matchGlob("a/c", "!(a|b)c", "bash")).toBe(false);
	});
});
