#!/usr/bin/env node
// Regenerates src/_east-asian-width.generated.ts from the Unicode
// Character Database's EastAsianWidth.txt — merged ranges of code points
// whose East_Asian_Width property is "W" (Wide) or "F" (Fullwidth), the only
// two categories `visibleWidth` treats as occupying two terminal columns.
//
// Run manually to pick up a new Unicode release:
//   yarn workspace @ac-kit/format-monospace run generate:east-asian-width
//
// Needs network access (fetches the pinned Unicode version below); the
// generated file IS committed, so no other build step ever needs network
// access to produce a working package.

import { writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";

import { mergeIntervals } from "@ac-kit/algo";
import { compareNaturalAscending } from "@ac-kit/core";

const UNICODE_VERSION = "17.0.0";
const SOURCE_URL = `https://www.unicode.org/Public/${UNICODE_VERSION}/ucd/EastAsianWidth.txt`;

// Unassigned code points in these blocks default to "W" and are never listed
// explicitly — see the "@missing" defaults documented in the file's own
// header comment.
const DEFAULT_WIDE_RANGES = [
	0x3400, 0x4dbf, 0x4e00, 0x9fff, 0xf900, 0xfaff, 0x20000, 0x2fffd, 0x30000,
	0x3fffd,
];

const packageRoot = fileURLToPath(new URL("..", import.meta.url)).replace(
	/\/$/,
	"",
);
const outPath = `${packageRoot}/src/_east-asian-width.generated.ts`;

const response = await fetch(SOURCE_URL);
if (!response.ok) {
	throw new Error(`Failed to fetch ${SOURCE_URL}: ${response.status}`);
}

const text = await response.text();
const ranges = [...DEFAULT_WIDE_RANGES];

for (const line of text.split("\n")) {
	const withoutComment = line.split("#")[0]?.trim();
	if (!withoutComment) {
		continue;
	}

	const [codeRange, category] = withoutComment
		.split(";")
		.map((field) => field.trim());
	if (category !== "W" && category !== "F") {
		continue;
	}

	const [startHex, endHex] = (codeRange ?? "").split("..");
	const start = Number.parseInt(startHex ?? "", 16);
	const end = endHex ? Number.parseInt(endHex, 16) : start;
	ranges.push(start, end);
}

// Code points are discrete, so abutting ranges coalesce too.
const flat = mergeIntervals(
	ranges,
	compareNaturalAscending,
	(end, nextStart) => nextStart === end + 1,
);

await writeFile(
	outPath,
	`// Generated by \`yarn workspace @ac-kit/format-monospace run generate:east-asian-width\`
// from ${SOURCE_URL} (Unicode ${UNICODE_VERSION}). Do not edit by hand.
//
// Flat, sorted [start, end, start, end, ...] code point ranges whose
// East_Asian_Width is "W" (Wide) or "F" (Fullwidth) — every other code point
// occupies a single terminal column. See \`visible-width.ts\`.
export default ${JSON.stringify(flat)};
`,
);

console.log(
	`✓  ${outPath}  (${flat.length / 2} ranges, ${flat.length} numbers)`,
);
