import { describe, expect, it } from "vitest";
import { replaceDiacritics } from "./replace-diacritics.js";

describe("replaceDiacritics", () => {
	it("should replace diacritics correctly", () => {
		expect(replaceDiacritics("àáâäæãåā")).toBe("aaaaaeaaa");
		expect(replaceDiacritics("çćčĉċ")).toBe("ccccc");
		expect(replaceDiacritics("ďđð")).toBe("ddd");
		expect(replaceDiacritics("èéêëēėę")).toBe("eeeeeee");
		expect(replaceDiacritics("ƒ")).toBe("f");
		expect(replaceDiacritics("ĝğġģ")).toBe("gggg");
		expect(replaceDiacritics("ĥħ")).toBe("hh");
		expect(replaceDiacritics("ìíîïīįı")).toBe("iiiiiii");
		expect(replaceDiacritics("ĵ")).toBe("j");
		expect(replaceDiacritics("ķ")).toBe("k");
		expect(replaceDiacritics("ĺļľł")).toBe("llll");
		expect(replaceDiacritics("ñńňņŋ")).toBe("nnnnn");
		expect(replaceDiacritics("òóôöøōőŏ")).toBe("oooooooo");
		expect(replaceDiacritics("œ")).toBe("oe");
		expect(replaceDiacritics("ŕřŗ")).toBe("rrr");
		expect(replaceDiacritics("śšşŝș")).toBe("sssss");
		expect(replaceDiacritics("ťţțŧ")).toBe("tttt");
		expect(replaceDiacritics("ùúûüūůűŭũų")).toBe("uuuuuuuuuu");
		expect(replaceDiacritics("ŵ")).toBe("w");
		expect(replaceDiacritics("ýÿŷ")).toBe("yyy");
		expect(replaceDiacritics("žżź")).toBe("zzz");
		expect(replaceDiacritics("ÀÁÂÄÆÃÅĀ")).toBe("AAAAAEAAA");
		expect(replaceDiacritics("ÇĆČĈĊ")).toBe("CCCCC");
		expect(replaceDiacritics("ĎĐÐ")).toBe("DDD");
		expect(replaceDiacritics("ÈÉÊËĒĖĘ")).toBe("EEEEEEE");
		expect(replaceDiacritics("ĜĞĠĢ")).toBe("GGGG");
		expect(replaceDiacritics("ĤĦ")).toBe("HH");
		expect(replaceDiacritics("ÌÍÎÏĪĮİ")).toBe("IIIIIII");
		expect(replaceDiacritics("Ĵ")).toBe("J");
		expect(replaceDiacritics("Ķ")).toBe("K");
		expect(replaceDiacritics("ĹĻĽŁ")).toBe("LLLL");
		expect(replaceDiacritics("ÑŃŇŅŊ")).toBe("NNNNN");
		expect(replaceDiacritics("ÒÓÔÖØŌŐŎ")).toBe("OOOOOOOO");
		expect(replaceDiacritics("Œ")).toBe("OE");
		expect(replaceDiacritics("ŔŘŖ")).toBe("RRR");
		expect(replaceDiacritics("ŚŠŞŜȘ")).toBe("SSSSS");
		expect(replaceDiacritics("ŤŢȚŦ")).toBe("TTTT");
		expect(replaceDiacritics("ÙÚÛÜŪŮŰŬŨŲ")).toBe("UUUUUUUUUU");
		expect(replaceDiacritics("Ŵ")).toBe("W");
		expect(replaceDiacritics("ÝŸŶ")).toBe("YYY");
		expect(replaceDiacritics("ŽŻŹ")).toBe("ZZZ");
		expect(replaceDiacritics("Hello, World!")).toBe("Hello, World!");
		expect(replaceDiacritics("Café à la mode.")).toBe("Cafe a la mode.");
		expect(replaceDiacritics("Đorđe Ćosić")).toBe("Dorde Cosic");
	});
});
