name: Validate

on:
  push:
    branches: [ '!main', 'v[0-9]+', 'v[0-9]+.[0-9]+' ]
    tags-ignore: [ 'v[0-9]+.[0-9]+.[0-9]+' ]
  pull_request:

jobs:
  validate:
    uses: anthochamp/dev-toolbox/.github/workflows/node-validate.yml@3bea5f586037d933601c8e045fe27df00b82b0c9
    with:
      node-package-manager: 'yarn'
