name: Validate

on:
  push:
    branches: ["main", "v[0-9]+", "v[0-9]+.[0-9]+"]
    tags-ignore: ["v[0-9]+.[0-9]+.[0-9]+"]
  pull_request:

jobs:
  validate:
    uses: anthochamp/dev-toolbox/.github/workflows/node-validate.yml@190998d2269b0f87e1bd7d39f4b08ef98b8783df # main
    with:
      node-package-manager: "yarn"
